export const IMAGES = {
  auth: {
    logo: require('./logo.png'),
    logo_whitebg: require('./logo_whitebg.png'),
    slider: require('./slider.png'),
    intro_image_1: require('./intro_image_1.jpg'),
    intro_image_2: require('./intro_image_2.jpg'),
    intro_image_3: require('./intro_image_3.jpg'),
    hayti_icon_white_bg_rounded: require('./hayti_icon_white_background_round.png'),
    email_icon: require('./email_icon.png'),
    google_icon: require('./google_icon.png'),
    apple_icon: require('./apple_icon.png'),
    twitter_x_icon: require('./twitter_x_icon.png'),
  },
  dash: {
    home_icon: require('./home/home_icon.png'),
    profile_icon: require('./home/profile_icon.png'),
    news_icon: require('./home/news_icon.png'),
    podcasts_icon: require('./home/podcasts_icon.png'),
    bell_icon: require('./home/bell.png'),
    location_icon: require('./home/location_pin_icon.png'),
    instagram_icon: require('./home/instagram_icon.png'),
    facebook_icon: require('./home/facebook_icon.png'),
    star_outline: require('./home/star-outline.png'),
    info_icon: require('./home/information-icon.png'),
    right_arrow: require('./home/right-arrow.png'),
    sun_icon: require('./home/sun-filled.png'),
    moon_icon: require('./home/moon-filled.png'),
    night_mode_icon: require('./home/night-mode.png'),
  },
};
