name: Android APK Build

on:
  workflow_run:
    workflows: ['Build and Analyze']
    types: [completed]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        node-version: [20.x] # Node.js version for React Native

    env:
      ANDROID_API_LEVEL: 35
      ANDROID_BUILD_TOOLS: '35.0.0'
      ANDROID_NDK: '27.1.12297006'

    steps:
      # ✅ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # ✅ Install dependencies
      - name: Install dependencies
        run: yarn install

      # ✅ Cache Gradle dependencies for faster builds
      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/caches/modules-2/files-2.1/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # ✅ Set up Java 17 (Recommended for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17' # Java 17 is more stable for Android builds

      # ✅ Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS }}
          ndk: ${{ env.ANDROID_NDK }}

      # ✅ Build the Android APK
      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --parallel --daemon || exit 1

      # ✅ Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      # ✅ Add Build Summary
      - name: Build Summary
        run: |
          echo "## Android Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **APK Generated:** app-release.apk ✅" >> $GITHUB_STEP_SUMMARY
          echo "- **Gradle Cache Used:** Enabled ⚡" >> $GITHUB_STEP_SUMMARY
          echo "- **Java Version:** 17 ☕" >> $GITHUB_STEP_SUMMARY
          echo "- **SonarQube Status:** Passed ✅" >> $GITHUB_STEP_SUMMARY
