name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    # Use ubuntu-latest for better compatibility, speed, and cost-effectiveness
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # SonarQube needs the full history to assign issues and authors correctly
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Version from your package.json engines field
          node-version: '20.18.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests and generate coverage report
        run: yarn test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Signal SonarQube Success
        run: echo "SonarQube analysis completed successfully"
        if: success()

  sonarqube-success:
    name: SonarQube Analysis Success
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'
    steps:
      - name: SonarQube Analysis Passed
        run: echo "SonarQube analysis passed - Android build can proceed"
